name: WeSOMMA
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  datetime_picker_formfield: ^1.0.0
  month_picker_dialog: 0.4.0
  http: 0.13.3
  http_interceptor:
  path:
  charts_flutter: 0.10.0
  provider: ^4.3.3
  cupertino_icons: ^1.0.0
  random_color: ^1.0.5
  flutter_rounded_progress_bar: ^0.2.0
  flutter_masked_text: ^0.8.0


dev_dependencies:
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/wesomma_icon.png"
  image_path_android: "assets/images/wesomma_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Monteserrat-Regular.ttf
      - asset: fonts/Monteserrat-Bold.ttf
        weigth: 700
  - family: Quicksand
    fonts:
      - asset: fonts/Quicksand-Regular.ttf
      - asset: fonts/Quicksand-Bold.ttf
        weigth: 700